### ISSUE TITLE
Can I get a API that provide a random voice URL？

### ISSUE THREAD

**Issue by OneTrueSum95** [mdiller/vue.dotabase.dillerm.io#1]
I can no longer play Dota 2 after my eye surgery, but I still enjoy listening to the voices of these heroes.

**Comment by mdiller** [comment]
Yeah sure! Are you just looking for an api endpoint that you're plugging into code somewhere? If so You can do something like this:
https://dotabase.dillerm.io/api/sql?query=SELECT%20mp3%20from%20responses%20order%20by%20random()%20limit%201
And then just add `https://dotabase.dillerm.io/vpk` to the beginning of the path it gives you to create the url.

Or are you looking for a url you can go to that will directly return an audio like this:
https://dotabase.dillerm.io/vpk/sounds/vo/pugna/pugna_ability_nblast_06.mp3
But except you want it give you a different one every time? If that's what you're looking for (or if its something else entirely) I could implement that pretty easy, just let me know!

**Comment by OneTrueSum95** [comment]
Thank you! That's all I want

**Comment by mdiller** [comment]
This is all you want?
https://dotabase.dillerm.io/api/sql?query=SELECT%20mp3%20from%20responses%20order%20by%20random()%20limit%201

Or do you mean the second thing i suggested?

**Comment by OneTrueSum95** [comment]
This is already perfect. I know a bit of frontend so I'll be able to work with it. Your help already means a lot to me!

**Comment by mdiller** [comment]
Great! I'm happy to help! :)
